<?xml version="1.0" encoding="utf-8"?><Database Name="Bon" Class="dbShopBonDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-94IGQTP\SQLEXPRESS;Initial Catalog=Bon;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BonConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="UserAdmin" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PassAdmin" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Hoten" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Categorys" Member="Categories">
    <Type Name="Category">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Slug" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Orders" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Img" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MetaKey" Type="System.String" DbType="NVarChar(155) NOT NULL" CanBeNull="false" />
      <Column Name="MetaDesc" Type="System.String" DbType="NVarChar(155) NOT NULL" CanBeNull="false" />
      <Column Name="Created_By" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Created_At" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Updated_By" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Updated_At" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Category_Product" Member="Products" ThisKey="Id" OtherKey="CatId" Type="Product" />
      <Association Name="User_Category" Member="User" ThisKey="Created_By" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="User_Category1" Member="User1" ThisKey="Status" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Contacts" Member="Contacts">
    <Type Name="Contact">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Detail" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateContact" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Updated_By" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Updated_At" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_Contact" Member="User" ThisKey="Status" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="User_Contact1" Member="User1" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Links" Member="Links">
    <Type Name="Link">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Slug" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="TypeLink" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="TableId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Menus" Member="Menus">
    <Type Name="Menus">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Link" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Orders" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MenuType" Type="System.String" DbType="VarChar(155) NOT NULL" CanBeNull="false" />
      <Column Name="Position" Type="System.String" DbType="VarChar(155) NOT NULL" CanBeNull="false" />
      <Column Name="TableId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Created_By" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Created_At" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Updated_By" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Updated_At" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_Menus" Member="User" ThisKey="Created_By" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="User_Menus1" Member="User1" ThisKey="Status" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Orderdetails" Member="Orderdetails">
    <Type Name="Orderdetail">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Soluong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PriceBuy" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Order_Orderdetail" Member="Order" ThisKey="OrderId" OtherKey="Id" Type="Order" IsForeignKey="true" />
      <Association Name="Product_Orderdetail" Member="Product" ThisKey="ProductId" OtherKey="Id" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Order">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateOrder" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Updated_At" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DaThanhToan" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TinhTrangGiaoHang" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Order_Orderdetail" Member="Orderdetails" ThisKey="Id" OtherKey="OrderId" Type="Orderdetail" />
    </Type>
  </Table>
  <Table Name="dbo.Posts" Member="Posts">
    <Type Name="Post">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TopicId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Slug" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Detail" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Img" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PostType" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MetaKey" Type="System.String" DbType="NVarChar(155)" CanBeNull="true" />
      <Column Name="MetaDesc" Type="System.String" DbType="NVarChar(155)" CanBeNull="true" />
      <Column Name="Created_By" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Created_At" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Updated_By" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Updated_At" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_Post" Member="User" ThisKey="Created_By" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="User_Post1" Member="User1" ThisKey="Status" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CatId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Slug" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Detail" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PriceBuy" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Img" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Created_At" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Product_Orderdetail" Member="Orderdetails" ThisKey="Id" OtherKey="ProductId" Type="Orderdetail" />
      <Association Name="Category_Product" Member="Category" ThisKey="CatId" OtherKey="Id" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductSales" Member="ProductSales">
    <Type Name="ProductSale">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PriceSale" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DateBegin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sliders" Member="Sliders">
    <Type Name="Slider">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Link" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Img" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Position" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Orders" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Created_By" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Created_At" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Updated_By" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Updated_At" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_Slider" Member="User" ThisKey="Created_By" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="User_Slider1" Member="User1" ThisKey="Status" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Topics" Member="Topics">
    <Type Name="Topic">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Slug" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Orders" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MetaKey" Type="System.String" DbType="NVarChar(155)" CanBeNull="true" />
      <Column Name="MetaDesc" Type="System.String" DbType="NVarChar(155)" CanBeNull="true" />
      <Column Name="Created_By" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Created_At" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Updated_By" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Updated_At" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_Topic" Member="User" ThisKey="Status" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="User_Topic1" Member="User1" ThisKey="Created_By" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(225) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Created_At" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="User_Category" Member="Categories" ThisKey="Id" OtherKey="Created_By" Type="Category" />
      <Association Name="User_Category1" Member="Categories1" ThisKey="Id" OtherKey="Status" Type="Category" />
      <Association Name="User_Contact" Member="Contacts" ThisKey="Id" OtherKey="Status" Type="Contact" />
      <Association Name="User_Contact1" Member="Contacts1" ThisKey="Id" OtherKey="UserId" Type="Contact" />
      <Association Name="User_Menus" Member="Menus" ThisKey="Id" OtherKey="Created_By" Type="Menus" />
      <Association Name="User_Menus1" Member="Menus1" ThisKey="Id" OtherKey="Status" Type="Menus" />
      <Association Name="User_Post" Member="Posts" ThisKey="Id" OtherKey="Created_By" Type="Post" />
      <Association Name="User_Post1" Member="Posts1" ThisKey="Id" OtherKey="Status" Type="Post" />
      <Association Name="User_Slider" Member="Sliders" ThisKey="Id" OtherKey="Created_By" Type="Slider" />
      <Association Name="User_Slider1" Member="Sliders1" ThisKey="Id" OtherKey="Status" Type="Slider" />
      <Association Name="User_Topic" Member="Topics" ThisKey="Id" OtherKey="Status" Type="Topic" />
      <Association Name="User_Topic1" Member="Topics1" ThisKey="Id" OtherKey="Created_By" Type="Topic" />
    </Type>
  </Table>
</Database>